### ISSUE TITLE
what is the instanceConfig

### ISSUE THREAD

**Issue by myNameIsDu** [Tirke/node-cache-manager-stores#102]
Sorry to bother you, I'm new in Redis, I use this library to connect Redis in Nextjs, And in my project, I have to support single-point and Cluster two modes. the Cluster is ok, But the single-point mode isn't working, and then I delete `instanceConfig`.  It's working
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/53305259/208065024-fa9aa7c1-0d62-41c9-9a8f-2ac76c3339eb.png">
Here's my change, I wonder what the `instanceConfig` is and how it's different from the default

**Comment by Tirke** [comment]
Hello @myNameIsDu both ways should be the same instanceConfig is a way to pass config in an object for better _isolation_ of types. If you look at tests you'll see that instanceConfig should work the same way as your green example.

**Comment by myNameIsDu** [comment]
wow, Thanks for your reply, I'll try it.
