### ISSUE TITLE
Seconds vs Milliseconds

### ISSUE THREAD

**Issue by bneigher** [Tirke/node-cache-manager-stores#331]
According to some documentation on cache-manager, it looks like they have moved to milliseconds from seconds from version 4 to 5: 
- https://github.com/node-cache-manager/node-cache-manager
- https://docs.nestjs.com/techniques/caching

I'm sending the values in to cache something with milliseconds and I'm getting very high ttl values in redis.  Is there some specification on whether we should be using seconds vs milliseconds?

```typescript
const CACHE_TTL_ROLES = 60 * 5 * 1000 // 5 Mins
```

```typescript
await this.cacheManager.set(localCacheKey, response.data, CACHE_TTL_ROLES)
 ```
 
```shell
redis> ttl "MY-KEY"
(integer) 299987 (300000)
```

**Comment by jonathanarezki** [comment]
As it looks like in the code, the ttl gets forwarded directly to ioredis.
But since ioredis is taking ttl as seconds instead of milliseconds, this creates issues.

**Comment by Tirke** [comment]
Yes lib will forward directly to ioredis so it's still seconds :)
