### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by vz-tl** [Tirke/node-cache-manager-stores#464]
This repo respectively its npm package is missing license information. 

I am using your  package in a project where we have to run a license check on installed npm packages, but without license info being added for your npm package, the check fails and I have to exclude the package from the checks which can become troublesome to continue using it without having a clear license definition.

As this package is based on https://github.com/dabroek/node-cache-manager-ioredis, I'd assume you will just continue using same license format as its predecessor, which is MIT.

So, I'd be glad if you could add a license definition in form of a LICENSE.md to the repo respectively npm package.

**Comment by Tirke** [comment]
I will add a licence ASAP sorry for that

**Comment by vz-tl** [comment]
No sorry please! But thanks a lot!

**Comment by Tirke** [comment]
Add License field in package.json and a License file to each packages :)
