### ISSUE TITLE
Cannot set TTL for Redis Cluster

### ISSUE THREAD

**Issue by ns-ochao** [Tirke/node-cache-manager-stores#629]
With standalone Redis, TTL can be set with the below cacheConfig
```
{
  ttl: 1800,
  store: ... ,
  host: 'localhost',
  port: '6379',
  ...
}
```
However for Redis Cluster, setting the below cacheConfig will not have TTL set
```
{
  ttl: 1800,
  store: ... ,
  clusterConfig: {
    nodes: [
      {
        host: ...,
        port: ...,
      },
      {
        host: ...,
        port: ...,
      }, ...
    ],
    options: { ... },
  }
  ...
}
```

Is there a way to set TTL for Redis Cluster? Or is it not supported?

cache-manager-ioredis@2.1.0

**Comment by Tirke** [comment]
I will look into that soon sorry for the delay

**Comment by Tirke** [comment]
I tested with a local redis cluster @ns-ochao and the ttl does work. 
How do you know it's not working?
